# Generated by Django 4.2.3 on 2023-07-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='productimported',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='productsoldout',
            name='user_created',
        ),
    ]
